{{- if .Values.initdb.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mongodb-database.fullname" . }}-initdb
  labels:
    {{- include "mongodb-database.labels" . | nindent 4 }}
data:
  {{- range $key, $value := .Values.initdb.scripts }}
  {{ $key }}: |
    {{- $value | nindent 4 }}
  {{- end }}
{{- end }}
